apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: dev 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: node-container
        image: omarkamal1/nodeapp:1.0
        ports:
         - containerPort: 3000
           protocol: TCP

